services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=prabu
      - POSTGRES_PASSWORD=prabu1234
      - POSTGRES_DB=backend_db

volumes:
  postgres_data: