services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      cache_from:
        - "${BACKEND_IMAGE}"
    image: "${BACKEND_IMAGE}"
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      - DEBUG=False
      - SQL_ENGINE=django.db.backends.postgresql
      - DATABASE=postgres
      - SECRET_KEY=${{ secrets.SECRET_KEY }}
      - SQL_DATABASE=${{ secrets.SQL_DATABASE }}
      - SQL_USER=${{ secrets.SQL_USER }}
      - SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}
      - SQL_HOST=${{ secrets.SQL_HOST }}
      - SQL_PORT=${{ secrets.SQL_PORT }}
  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    ports:
      - 80:80
    depends_on:
      - backend